version: 2

models:
  - name: stg_supplychain
    columns:
      - name: order_id
        tests:
          - unique # Đảm bảo mã đơn hàng không bị trùng
          - not_null # Đảm bảo không có đơn hàng nào bị thiếu mã
      - name: sales_amount
        tests:
          - accepted_values:
              values: [0] # Bạn có thể kiểm tra xem doanh thu có âm hay không (nếu cần)
