version: 2

models:
  - name: stg_supplychain
    description: "Bang clean tang Silver cua Supply Chain"
    columns:
      - name: order_id
        description: "Ma don hang"
        tests:
          - not_null  # Giữ lại test này vì mã đơn hàng không được để trống